package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'RunTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("RunTests")) {
    expectSteps {
        script {
            name = "hello world"
            enabled = false
            scriptContent = "echo hello world"
        }
        maven {
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            mavenVersion = defaultProvidedVersion()
        }
    }
    steps {
        update<MavenBuildStep>(1) {
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
        }
    }
}
